version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000
    environment:
      - NODE_ENV=development
    deploy:
      replicas: 3
      restart_policy:
        condition: always
    networks:
      - mynetwork
  nginx:
    image: nginx
    restart: 'always'
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web    
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge

